// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7HJdg65eBGHiqVOk5MXAjxFdGbjmE5Aw',
    appId: '1:190431718250:web:af26bd1b39c9525be7d313',
    messagingSenderId: '190431718250',
    projectId: 'todo-ee7ee',
    authDomain: 'todo-ee7ee.firebaseapp.com',
    storageBucket: 'todo-ee7ee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOaxsW9R3JnFL7TGyiqS6Ahy4lVZqGMc',
    appId: '1:190431718250:android:345ab7f8ead9141fe7d313',
    messagingSenderId: '190431718250',
    projectId: 'todo-ee7ee',
    storageBucket: 'todo-ee7ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMTi-Mtisjy1MBqH0MIRIRH_M0GCtUJd8',
    appId: '1:190431718250:ios:fdd451a63c2b09c0e7d313',
    messagingSenderId: '190431718250',
    projectId: 'todo-ee7ee',
    storageBucket: 'todo-ee7ee.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
